
export type TOrder = {
    email: string;
    product: string, // This will reference the Product model
    quantity: number;
    totalPrice: number;
    createdAt: Date; // Automatically generated by Mongoose
    updatedAt: Date; // Automatically generated by Mongoose
}
